import unittest
import os
from unittest.mock import patch, mock_open
from datetime import datetime
from src.lint_roller import analyze_gitignore

class TestCosmicLintRoller(unittest.TestCase):

    @patch('os.path.exists')
    @patch('builtins.open', new_callable=mock_open)
    @patch('src.lint_roller.datetime') # Mock datetime for deterministic output
    def test_empty_gitignore(self, mock_dt, mock_file_open, mock_exists):
        # Mock rationale: Ensure os.path.exists returns True for the file path
        # Mock rationale: Simulate an empty .gitignore file content
        # Mock rationale: Fix datetime output for consistent test results
        mock_exists.return_value = True
        mock_file_open.return_value.read.return_value = ""
        mock_dt.now.return_value = datetime(2023, 1, 1, 12, 0, 0)

        report = analyze_gitignore(".gitignore")

        self.assertEqual(report["original_line_count"], 0)
        self.assertEqual(report["unique_patterns_found"], 0)
        self.assertEqual(report["duplicates_removed"], 0)
        self.assertFalse(report["lines_sorted"])
        expected_suggested = (
            "# Generated by Cosmic Lint Roller\n"
            "# Cleaned on 2023-01-01 12:00:00\n"
            "\n"
        )
        self.assertEqual(report["suggested_content"], expected_suggested)

    @patch('os.path.exists')
    @patch('builtins.open', new_callable=mock_open)
    @patch('src.lint_roller.datetime')
    def test_basic_deduplication_and_sorting(self, mock_dt, mock_file_open, mock_exists):
        # Mock rationale: Simulate a .gitignore with duplicates and unsorted entries
        # Mock rationale: Fix datetime output for consistent test results
        mock_exists.return_value = True
        mock_file_open.return_value.read.return_value = (
            "*.log\n"
            "node_modules/\n"
            "*.pyc\n"
            "*.log\n" # Duplicate
            "__pycache__/\n"
            ".env\n"
        )
        mock_dt.now.return_value = datetime(2023, 1, 1, 12, 0, 0)

        report = analyze_gitignore(".gitignore")

        self.assertEqual(report["original_line_count"], 6)
        self.assertEqual(report["unique_patterns_found"], 5)
        self.assertEqual(report["duplicates_removed"], 1)
        self.assertTrue(report["lines_sorted"])
        expected_suggested = (
            "# Generated by Cosmic Lint Roller\n"
            "# Cleaned on 2023-01-01 12:00:00\n"
            "\n"
            "*.log\n"
            "*.pyc\n"
            ".env\n"
            "__pycache__/\n"
            "node_modules/"
        )
        self.assertEqual(report["suggested_content"], expected_suggested)

    @patch('os.path.exists')
    @patch('builtins.open', new_callable=mock_open)
    @patch('src.lint_roller.datetime')
    def test_with_comments_and_blank_lines(self, mock_dt, mock_file_open, mock_exists):
        # Mock rationale: Simulate a .gitignore with comments and blank lines
        # Mock rationale: Fix datetime output for consistent test results
        mock_exists.return_value = True
        mock_file_open.return_value.read.return_value = (
            "# Python specific files\n"
            "*.pyc\n"
            "__pycache__/\n"
            "\n"
            "# Node specific files\n"
            "node_modules/\n"
            "npm-debug.log\n"
            "*.log\n"
            "*.log\n" # Duplicate
        )
        mock_dt.now.return_value = datetime(2023, 1, 1, 12, 0, 0)

        report = analyze_gitignore(".gitignore")

        self.assertEqual(report["original_line_count"], 9)
        self.assertEqual(report["unique_patterns_found"], 5)
        self.assertEqual(report["duplicates_removed"], 1)
        self.assertTrue(report["lines_sorted"])
        expected_suggested = (
            "# Generated by Cosmic Lint Roller\n"
            "# Cleaned on 2023-01-01 12:00:00\n"
            "\n"
            "*.log\n"
            "*.pyc\n"
            "__pycache__/\n"
            "node_modules/\n"
            "npm-debug.log"
        )
        self.assertEqual(report["suggested_content"], expected_suggested)

    @patch('os.path.exists')
    @patch('builtins.open', new_callable=mock_open)
    @patch('src.lint_roller.datetime')
    def test_file_not_found(self, mock_dt, mock_file_open, mock_exists):
        # Mock rationale: Simulate a scenario where the .gitignore file does not exist
        # Mock rationale: Fix datetime output for consistent test results
        mock_exists.return_value = False
        mock_dt.now.return_value = datetime(2023, 1, 1, 12, 0, 0)

        report = analyze_gitignore("non_existent_file.gitignore")

        self.assertEqual(report["original_line_count"], 0)
        self.assertEqual(report["unique_patterns_found"], 0)
        self.assertEqual(report["duplicates_removed"], 0)
        self.assertFalse(report["lines_sorted"])
        expected_suggested = (
            "# Generated by Cosmic Lint Roller\n"
            "# Cleaned on 2023-01-01 12:00:00\n"
            "\n"
        )
        self.assertEqual(report["suggested_content"], expected_suggested)
        mock_file_open.assert_not_called() # Ensure open was not called if file doesn't exist

    @patch('os.path.exists')
    @patch('builtins.open', new_callable=mock_open)
    @patch('src.lint_roller.datetime')
    def test_only_comments_and_blanks(self, mock_dt, mock_file_open, mock_exists):
        # Mock rationale: Simulate a .gitignore file containing only comments and blank lines
        # Mock rationale: Fix datetime output for consistent test results
        mock_exists.return_value = True
        mock_file_open.return_value.read.return_value = (
            "# This is a comment\n"
            "\n"
            "  # Another comment with leading spaces\n"
            "\n"
        )
        mock_dt.now.return_value = datetime(2023, 1, 1, 12, 0, 0)

        report = analyze_gitignore(".gitignore")

        self.assertEqual(report["original_line_count"], 4)
        self.assertEqual(report["unique_patterns_found"], 0)
        self.assertEqual(report["duplicates_removed"], 0)
        self.assertFalse(report["lines_sorted"])
        expected_suggested = (
            "# Generated by Cosmic Lint Roller\n"
            "# Cleaned on 2023-01-01 12:00:00\n"
            "\n"
        )
        self.assertEqual(report["suggested_content"], expected_suggested)

    @patch('os.path.exists')
    @patch('builtins.open', new_callable=mock_open)
    @patch('src.lint_roller.datetime')
    def test_case_insensitive_sorting(self, mock_dt, mock_file_open, mock_exists):
        # Mock rationale: Simulate .gitignore with patterns that test case-insensitive sorting
        # Mock rationale: Fix datetime output for consistent test results
        mock_exists.return_value = True
        mock_file_open.return_value.read.return_value = (
            "Foo.txt\n"
            "bar.txt\n"
            "baz.txt\n"
        )
        mock_dt.now.return_value = datetime(2023, 1, 1, 12, 0, 0)

        report = analyze_gitignore(".gitignore")

        self.assertEqual(report["original_line_count"], 3)
        self.assertEqual(report["unique_patterns_found"], 3)
        self.assertEqual(report["duplicates_removed"], 0)
        self.assertTrue(report["lines_sorted"])
        expected_suggested = (
            "# Generated by Cosmic Lint Roller\n"
            "# Cleaned on 2023-01-01 12:00:00\n"
            "\n"
            "bar.txt\n"
            "baz.txt\n"
            "Foo.txt"
        )
        self.assertEqual(report["suggested_content"], expected_suggested)
