FROM python:3.9-slim-buster

WORKDIR /app

COPY src/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt pytest

COPY src/app.py src/
COPY tests/test_app.py tests/

CMD ["pytest", "tests/test_app.py"]
