variable "bucket_name" {
  description = "Name of the S3 bucket that will act as the secret vault."
  type        = string
}

variable "password_length" {
  description = "Length of the autogenerated password (min 8, max 64)."
  type        = number
  default     = 16
  validation {
    condition     = var.password_length >= 8 && var.password_length <= 64
    error_message = "password_length must be between 8 and 64."
  }
}
