import os
import json
import argparse
from datetime import datetime

def get_file_state(root_dir):
    """Scans the directory and returns a dictionary of file paths to their state (mtime, size)."""
    current_state = {}
    for dirpath, _, filenames in os.walk(root_dir):
        for filename in filenames:
            filepath = os.path.join(dirpath, filename)
            try:
                # Normalize path to be relative to root_dir for consistent state tracking
                relative_filepath = os.path.relpath(filepath, root_dir)
                stat = os.stat(filepath)
                current_state[relative_filepath] = {
                    'mtime': stat.st_mtime,
                    'size': stat.st_size
                }
            except OSError: # File might have been deleted between walk and stat
                continue
    return current_state

def load_previous_state(state_file_path):
    """Loads the previous state from a JSON file."""
    if os.path.exists(state_file_path):
        with open(state_file_path, 'r') as f:
            return json.load(f)
    return {}

def save_current_state(state_file_path, current_state):
    """Saves the current state to a JSON file."""
    with open(state_file_path, 'w') as f:
        json.dump(current_state, f, indent=2)

def generate_digest_report(root_dir, previous_state, current_state):
    """Compares states and generates a markdown report."""
    new_files = []
    modified_files = []
    deleted_files = []

    # Check for new and modified files
    for filepath, current_props in current_state.items():
        if filepath not in previous_state:
            new_files.append(filepath)
        else:
            previous_props = previous_state[filepath]
            if (current_props['mtime'] != previous_props['mtime'] or
                    current_props['size'] != previous_props['size']):
                modified_files.append(f"{filepath} (Modified on {datetime.fromtimestamp(current_props['mtime']).strftime('%Y-%m-%d %H:%M:%S')})")

    # Check for deleted files
    for filepath in previous_state:
        if filepath not in current_state:
            deleted_files.append(filepath)

    report_date = datetime.now().strftime('%Y-%m-%d')
    report_content = [
        f"# Doom Scroll Digest - {report_date}",
        f"\n## Changes Detected in {root_dir}"
    ]

    if new_files:
        report_content.append("\n### New Files:")
        for f in sorted(new_files):
            report_content.append(f"- `{f}`")
    if modified_files:
        report_content.append("\n### Modified Files:")
        for f in sorted(modified_files):
            report_content.append(f"- `{f}`")
    if deleted_files:
        report_content.append("\n### Deleted Files:")
        for f in sorted(deleted_files):
            report_content.append(f"- `{f}`")

    if not (new_files or modified_files or deleted_files):
        report_content.append("\n*No significant changes detected.*")

    report_content.append("\n---\n\n*Generated by ApocalypsAI Nightly Integrator*")

    return "\n".join(report_content)

def main():
    parser = argparse.ArgumentParser(
        description="Generate a daily digest of file system changes."
    )
    parser.add_argument(
        "--path",
        required=True,
        help="The root directory to scan for changes."
    )
    parser.add_argument(
        "--output-file",
        required=True,
        help="The path where the markdown digest report will be saved."
    )
    parser.add_argument(
        "--state-file",
        default=None,
        help="The path to store/load the previous state. Defaults to .doom_scroll_state.json in the --path directory."
    )

    args = parser.parse_args()

    root_dir = os.path.abspath(args.path)
    output_file = os.path.abspath(args.output_file)
    state_file = args.state_file
    if state_file is None:
        state_file = os.path.join(root_dir, '.doom_scroll_state.json')
    else:
        state_file = os.path.abspath(state_file)

    if not os.path.isdir(root_dir):
        print(f"Error: Directory not found at '{root_dir}'")
        exit(1)

    previous_state = load_previous_state(state_file)
    current_state = get_file_state(root_dir)

    report = generate_digest_report(root_dir, previous_state, current_state)

    os.makedirs(os.path.dirname(output_file), exist_ok=True)
    with open(output_file, 'w') as f:
        f.write(report)

    save_current_state(state_file, current_state)

    print(f"Doom Scroll Digest generated and saved to '{output_file}'")
    print(f"Current state saved to '{state_file}'")


if __name__ == '__main__':
    main()
