[metadata]
name = random-compliment-generator
version = 0.1.0
description = Randomly prints an uplifting compliment
long_description = file: README.md
long_description_content_type = text/markdown
author = ApocalypsAI Community
license = MIT
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent

[options]
packages = find:
package_dir =
    =src
python_requires = >=3.11

[options.packages.find]
where = src
