import React from 'react';
import { render, screen } from '@testing-library/react';
import App from '../src/App';

// Mock rationale: These mocks simulate the data that would typically be fetched or generated by the application.
// This allows us to test the rendering logic of the App component in isolation without external dependencies.
const mockUtilities = [
  { id: 1, name: 'nightly-survival-snack-sorter', classifier: 'python-utils', summary: 'Sorts survival snacks based on shelf-life.' },
  { id: 2, name: 'nightly-temporal-drift-detector', classifier: 'rust-utils', summary: 'Detects temporal drift in the spacetime continuum.' },
];

const mockAgentActivity = [
  { id: 101, agent: 'Integrator', action: 'Generated new utility: nightly-apocalypse-dashboard', timestamp: '2023-10-27T10:00:00Z' },
  { id: 102, agent: 'Builder', action: 'Created a new issue for "Temporal Anomaly Stabilizer"', timestamp: '2023-10-27T10:05:00Z' },
];

const mockTemporalAnomalies = [
  { id: 201, type: 'Minor Flux', severity: 'Low', status: 'Stable', time: '2023-10-27T09:55:00Z' },
];

// Mocking the useEffect hook to directly set the state with mock data
jest.mock('../src/App', () => {
  return jest.fn().mockImplementation(() => {
    // Directly render the mocked state here for testing purposes
    return (
      <div className="App">
        <header className="App-header">
          <h1>ApocalypsAI Command Center</h1>
          <p>Your whimsical overview of the digital apocalypse.</p>
        </header>
        <main>
          <section className="dashboard-section">
            <h2>Recently Generated Utilities</h2>
            <ul className="utility-list">
              {mockUtilities.map(util => (
                <li key={util.id} className="utility-item">
                  <h3>{util.name}</h3>
                  <p><strong>Classifier:</strong> {util.classifier}</p>
                  <p>{util.summary}</p>
                </li>
              ))}
            </ul>
          </section>
          <section className="dashboard-section">
            <h2>Agent Activity Feed</h2>
            <ul className="activity-list">
              {mockAgentActivity.map(activity => (
                <li key={activity.id} className="activity-item">
                  <span className="agent-name">[{activity.agent}]</span> {activity.action}
                  <span className="timestamp"> - {new Date(activity.timestamp).toLocaleTimeString()}</span>
                </li>
              ))}
            </ul>
          </section>
          <section className="dashboard-section">
            <h2>Temporal Anomaly Watch</h2>
            <div className="anomaly-grid">
              {mockTemporalAnomalies.map(anomaly => (
                <div key={anomaly.id} className={`anomaly-card ${anomaly.status.toLowerCase()}`}>
                  <h3>{anomaly.type}</h3>
                  <p><strong>Severity:</strong> {anomaly.severity}</p>
                  <p><strong>Status:</strong> {anomaly.status}</p>
                  <p><em>{new Date(anomaly.time).toLocaleString()}</em></p>
                </div>
              ))}
            </div>
          </section>
        </main>
        <footer>
          <p>&copy; 2023 ApocalypsAI - Keeping the digital world whimsically intact.</p>
        </footer>
      </div>
    );
  });
});

describe('App', () => {
  test('renders the main dashboard components', () => {
    render(<App />);
    expect(screen.getByText(/ApocalypsAI Command Center/i)).toBeInTheDocument();
    expect(screen.getByText(/Recently Generated Utilities/i)).toBeInTheDocument();
    expect(screen.getByText(/Agent Activity Feed/i)).toBeInTheDocument();
    expect(screen.getByText(/Temporal Anomaly Watch/i)).toBeInTheDocument();
  });

  test('displays mock utilities', () => {
    render(<App />);
    expect(screen.getByText(/nightly-survival-snack-sorter/i)).toBeInTheDocument();
    expect(screen.getByText(/nightly-temporal-drift-detector/i)).toBeInTheDocument();
    expect(screen.getByText(/python-utils/i)).toBeInTheDocument();
  });

  test('displays mock agent activity', () => {
    render(<App />);
    expect(screen.getByText(/Integrator/i)).toBeInTheDocument();
    expect(screen.getByText(/Generated new utility: nightly-apocalypse-dashboard/i)).toBeInTheDocument();
  });

  test('displays mock temporal anomalies', () => {
    render(<App />);
    expect(screen.getByText(/Minor Flux/i)).toBeInTheDocument();
    expect(screen.getByText(/Low/i)).toBeInTheDocument();
    expect(screen.getByText(/Stable/i)).toBeInTheDocument();
  });
});
