[package]
name = "temporal-file-forager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0", features = ["derive"] }
chrono = "0.4" # For human-readable timestamps

[dev-dependencies]
tempfile = "3.0"
filetime = "0.2" # For setting file modification times in tests
