#!/usr/bin/env bash

set -euo pipefail

# Default configuration
DEFAULT_MAX_AGE_DAYS=7
CACHE_DIR="${APT_CACHE_DIR:-/var/cache/apt/archives}"
DRY_RUN=false
INSTALL_CRON=false
MAX_AGE_DAYS=$DEFAULT_MAX_AGE_DAYS

# Simple apocalypse‑themed quotes
QUOTES=(
  "The sky cracks, but your disk stays clean."
  "Even the end of the world needs a tidy home."
  "Dust settles, packages vanish."
  "When the fire rains, your cache will be empty."
  "Apocalypse imminent – clear the clutter!"
)

print_usage() {
  cat <<'EOF'
Usage: cleanup.sh [options]

Options:
  --dry-run               Show what would be deleted without removing files.
  --max-age-days N        Delete .deb files older than N days (default: 7).
  --install-cron          Install a daily cron job at 02:00 running this script.
  -h, --help              Show this help message.
EOF
}

# Parse arguments
while (("$#")); do
  case "$1" in
    --dry-run) DRY_RUN=true ; shift ;;
    --install-cron) INSTALL_CRON=true ; shift ;;
    --max-age-days)
      if [[ -n "${2-}" && "$2" =~ ^[0-9]+$ ]]; then
        MAX_AGE_DAYS="$2"
        shift 2
      else
        echo "Error: --max-age-days requires a numeric argument" >&2
        exit 1
      fi
      ;;
    -h|--help) print_usage ; exit 0 ;;
    *) echo "Unknown option: $1" >&2 ; print_usage ; exit 1 ;;
  esac
done

# Helper to print a random apocalypse quote
random_quote() {
  local idx=$((RANDOM % ${#QUOTES[@]}))
  echo "${QUOTES[$idx]}"
}

# Main cleanup logic
perform_cleanup() {
  if [[ ! -d "$CACHE_DIR" ]]; then
    echo "Cache directory '$CACHE_DIR' does not exist. Nothing to do." >&2
    exit 0
  fi

  # Find stale .deb files
  mapfile -t stale_files < <(find "$CACHE_DIR" -type f -name "*.deb" -mtime +"$MAX_AGE_DAYS" -print)

  if [[ ${#stale_files[@]} -eq 0 ]]; then
    echo "No stale .deb files found (age > $MAX_AGE_DAYS days)."
    return
  fi

  echo "Found ${#stale_files[@]} stale .deb file(s):"
  for f in "${stale_files[@]}"; do
    echo "  $f"
  done

  if $DRY_RUN; then
    echo "Dry‑run mode – no files will be deleted."
  else
    echo "Deleting stale files..."
    for f in "${stale_files[@]}"; do
      rm -f "$f"
    done
    echo "Cleanup complete. $(random_quote)"
  fi
}

install_cron_job() {
  if [[ $EUID -ne 0 ]]; then
    echo "Cron installation requires root privileges. Please run with sudo." >&2
    exit 1
  fi

  local cron_path="/etc/cron.d/apt-cleanup"
  cat > "$cron_path" <<EOF
# Apt cache cleanup – generated by nightly-apt-cleanup-scheduler
0 2 * * * root ${0} --max-age-days $MAX_AGE_DAYS >> /var/log/apt-cleanup.log 2>&1
EOF
  chmod 644 "$cron_path"
  echo "Cron job installed at $cron_path (runs daily at 02:00)."
}

# Execute requested actions
if $INSTALL_CRON; then
  install_cron_job
fi

perform_cleanup
