import argparse
import os
from datetime import datetime

def analyze_gitignore(file_path: str) -> dict:
    """
    Analyzes a .gitignore file, identifies unique patterns, sorts them,
    and generates a suggested cleaned content.
    Does not modify the file.
    """
    original_lines = []
    if os.path.exists(file_path):
        with open(file_path, 'r') as f:
            original_lines = [line.strip() for line in f]

    patterns = set()
    for line in original_lines:
        if line and not line.startswith('#'):
            patterns.add(line)

    sorted_patterns = sorted(list(patterns), key=lambda s: s.lower())

    suggested_content_lines = [
        "# Generated by Cosmic Lint Roller",
        f"# Cleaned on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        "",
    ]
    suggested_content_lines.extend(sorted_patterns)

    report = {
        "original_content": "\n".join(original_lines),
        "suggested_content": "\n".join(suggested_content_lines),
        "original_line_count": len(original_lines),
        "unique_patterns_found": len(patterns),
        "duplicates_removed": len(original_lines) - len(patterns) if len(original_lines) > 0 else 0,
        "lines_sorted": True if len(patterns) > 1 else False, # Assume sorted if >1 pattern
        "file_path": file_path
    }
    return report

def main():
    parser = argparse.ArgumentParser(
        description="Cosmic Lint Roller: Clean up your .gitignore file."
    )
    parser.add_argument(
        "--file",
        type=str,
        default=".gitignore",
        help="Path to the .gitignore file to analyze."
    )
    args = parser.parse_args()

    report = analyze_gitignore(args.file)

    print("--- Cosmic Lint Roller Report ---")
    print(f"\nAnalyzing: {report['file_path']}")
    print(f"\nOriginal lines: {report['original_line_count']}")
    print(f"Unique patterns found: {report['unique_patterns_found']}")
    print(f"Duplicates removed: {report['duplicates_removed']}")
    print(f"Lines sorted: {'Yes' if report['lines_sorted'] else 'No/N/A'}")

    print("\nSuggested .gitignore content:")
    print(report['suggested_content'])

if __name__ == "__main__":
    main()
