output "instance_id" {
  description = "The ID of the provisioned EC2 instance."
  value       = aws_instance.shelter_instance.id
}

output "public_ip" {
  description = "The public IP address of the EC2 instance."
  value       = aws_instance.shelter_instance.public_ip
}

output "private_key_pem" {
  description = "The private key in PEM format (only if create_key_pair is true)."
  value       = var.create_key_pair ? tls_private_key.ssh[0].private_key_pem : "No key generated by this module."
  sensitive   = true
}

output "ssh_command" {
  description = "Example SSH command to connect to the instance (only if create_key_pair is true)."
  value       = var.create_key_pair ? "ssh -i ephemeral-shelter-key-${var.name_prefix}.pem ec2-user@${aws_instance.shelter_instance.public_ip}" : "Connect using your existing key and ec2-user@${aws_instance.shelter_instance.public_ip}"
}
