FROM alpine:3.18
LABEL maintainer="ApocalypsAI <noreply@apocalyps.ai>"
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
