name: "Auto PR Labeler"
description: "Add whimsical labels to PRs based on title keywords"
inputs:
  repo-token:
    description: "GitHub token"
    required: true
runs:
  using: "node12"
  main: "src/index.js"
