[all:children]
aws
azure
gcp
onprem

[aws]
aws-host1 ansible_host=10.0.1.10
aws-host2 ansible_host=10.0.1.11

[azure]
az-host1 ansible_host=10.0.2.10
az-host2 ansible_host=10.0.2.11

[gcp]
gcp-host1 ansible_host=10.0.3.10
gcp-host2 ansible_host=10.0.3.11

[onprem]
onprem-host1 ansible_host=192.168.1.10
onprem-host2 ansible_host=192.168.1.11
