import os
import shutil
import argparse
import sys

# Define common patterns for build artifacts and dependency caches
# These are directories or files that can typically be safely removed
# as they can be regenerated by build tools or package managers.
COMMON_ARTIFACT_PATTERNS = [
    "__pycache__",      # Python bytecode cache
    ".pytest_cache",    # pytest cache
    ".venv",            # Python virtual environment (directory)
    "venv",             # Python virtual environment (directory)
    "node_modules",     # Node.js dependencies
    "target",           # Rust build output, Maven build output
    "build",            # Gradle/Go build output, general build directory
    "dist",             # Distribution directory (Python, JS)
    ".DS_Store",        # macOS specific file
    "Thumbs.db",        # Windows specific file
    "vendor",           # Go dependencies (sometimes)
    "coverage",         # Coverage reports
    ".mypy_cache",      # MyPy cache
    ".ruff_cache",      # Ruff cache
]

def find_artifacts(root_dir, patterns=COMMON_ARTIFACT_PATTERNS):
    """
    Walks through the given root directory and identifies directories/files
    matching the specified artifact patterns.
    """
    found_paths = []
    for dirpath, dirnames, filenames in os.walk(root_dir):
        # Check for directory patterns
        for pattern in patterns:
            if pattern in dirnames:
                full_path = os.path.join(dirpath, pattern)
                found_paths.append(full_path)
                # Optimization: if a known artifact directory is found,
                # no need to walk into it further. Remove it from dirnames
                # to prevent os.walk from descending into it.
                dirnames[:] = [d for d in dirnames if d != pattern]
        
        # Check for file patterns (e.g., .DS_Store, Thumbs.db)
        for pattern in patterns:
            if pattern in filenames:
                full_path = os.path.join(dirpath, pattern)
                found_paths.append(full_path)
    return found_paths

def get_path_size(path):
    """
    Calculates the size of a file or directory in bytes.
    """
    if not os.path.exists(path):
        return 0
    if os.path.isfile(path):
        return os.path.getsize(path)
    
    total_size = 0
    for dirpath, dirnames, filenames in os.walk(path):
        for f in filenames:
            fp = os.path.join(dirpath, f)
            # Avoid following symlinks for size calculation to prevent infinite loops
            # and incorrect sizes for linked content.
            if not os.path.islink(fp):
                total_size += os.path.getsize(fp)
    return total_size

def clean_artifacts(paths_to_clean, dry_run=False):
    """
    Removes the specified paths.
    If dry_run is True, it only prints what would be removed.
    """
    cleaned_count = 0
    total_size_freed = 0

    for path in paths_to_clean:
        if not os.path.exists(path):
            print(f"Skipping non-existent path: {path}")
            continue

        try:
            size = get_path_size(path)
            total_size_freed += size
            size_mb = size / (1024 * 1024)

            if os.path.isdir(path):
                if dry_run:
                    print(f"[DRY RUN] Would remove directory: {path} ({size_mb:.2f} MB)")
                else:
                    print(f"Removing directory: {path} ({size_mb:.2f} MB)")
                    shutil.rmtree(path)
                    cleaned_count += 1
            elif os.path.isfile(path):
                if dry_run:
                    print(f"[DRY RUN] Would remove file: {path} ({size_mb:.2f} MB)")
                else:
                    print(f"Removing file: {path} ({size_mb:.2f} MB)")
                    os.remove(path)
                    cleaned_count += 1
        except OSError as e:
            print(f"Error removing {path}: {e}", file=sys.stderr)
    
    if not dry_run:
        print(f"\nCleaned {cleaned_count} items, freeing up {total_size_freed / (1024*1024):.2f} MB.")
    else:
        print(f"\n[DRY RUN] Would clean {cleaned_count} items, freeing up {total_size_freed / (1024*1024):.2f} MB.")

def main():
    parser = argparse.ArgumentParser(
        description="ApocalypsAI Post-Apocalyptic Package Purifier: Cleans up common build artifacts and dependency caches."
    )
    parser.add_argument(
        "path",
        nargs="?",
        default=".",
        help="The root directory to scan for artifacts (default: current directory)."
    )
    parser.add_argument(
        "--list",
        action="store_true",
        help="Only list the artifacts that would be cleaned, do not remove them (dry run)."
    )
    parser.add_argument(
        "--clean",
        action="store_true",
        help="Remove the identified artifacts. Use with caution!"
    )
    parser.add_argument(
        "--patterns",
        nargs=".", # Use '.' to allow zero or more arguments, but require at least one if present
        help=f"Override default patterns. Default: {', '.join(COMMON_ARTIFACT_PATTERNS)}"
    )

    args = parser.parse_args()

    if not args.list and not args.clean:
        print("Please specify either --list to see what would be cleaned, or --clean to actually remove items.", file=sys.stderr)
        sys.exit(1)

    target_patterns = args.patterns if args.patterns else COMMON_ARTIFACT_PATTERNS

    print(f"Scanning '{os.path.abspath(args.path)}' for artifacts matching: {', '.join(target_patterns)}")
    found_artifacts = find_artifacts(args.path, target_patterns)

    if not found_artifacts:
        print("No artifacts found matching the patterns.")
        sys.exit(0)

    print("\n--- Found Artifacts ---")
    for artifact in found_artifacts:
        print(artifact)
    print("-----------------------")

    if args.clean:
        print("\nInitiating cleanup...")
        clean_artifacts(found_artifacts, dry_run=False)
    elif args.list:
        print("\nDry run complete. Use --clean to remove these items.")
        clean_artifacts(found_artifacts, dry_run=True) # Still run dry_run to show sizes

if __name__ == "__main__":
    main()
