const { encodeMessage, decodeMessage } = require('../src/cosmicComm');

describe('Cosmic Comm Relay', () => {
  test('should encode and decode a simple message correctly', () => {
    const originalMessage = "Hello, cosmic traveler!";
    const encoded = encodeMessage(originalMessage);
    expect(typeof encoded).toBe('string');
    expect(encoded.length).toBeGreaterThan(0);

    const decoded = decodeMessage(encoded);
    expect(decoded).toBe(originalMessage);
  });

  test('should handle empty messages', () => {
    const originalMessage = "";
    const encoded = encodeMessage(originalMessage);
    expect(encoded).toBe("");
    const decoded = decodeMessage(encoded);
    expect(decoded).toBe("");
  });

  test('should handle messages with special characters', () => {
    const originalMessage = "!@#$%^&*()_+=-`~[]{}\\|;:'\",./<>?";
    const encoded = encodeMessage(originalMessage);
    expect(typeof encoded).toBe('string');
    expect(encoded.length).toBeGreaterThan(0);

    const decoded = decodeMessage(encoded);
    expect(decoded).toBe(originalMessage);
  });

  test('should handle messages with numbers', () => {
    const originalMessage = "1234567890";
    const encoded = encodeMessage(originalMessage);
    expect(typeof encoded).toBe('string');
    expect(encoded.length).toBeGreaterThan(0);

    const decoded = decodeMessage(encoded);
    expect(decoded).toBe(originalMessage);
  });

  test('should handle longer messages', () => {
    const originalMessage = "This is a much longer message to test the robustness of the cosmic communication relay. It should still be able to encode and decode accurately.";
    const encoded = encodeMessage(originalMessage);
    expect(typeof encoded).toBe('string');
    expect(encoded.length).toBeGreaterThan(0);

    const decoded = decodeMessage(encoded);
    expect(decoded).toBe(originalMessage);
  });

  test('should handle decoding of a known encoded string', () => {
    // This encoded string was generated by a previous run of encodeMessage("Test")
    // # Mock rationale: This is a fixed, known input/output pair for deterministic testing.
    const encodedString = "11-0|13-3|17-6|23-9";
    const expectedMessage = "Test";
    const decoded = decodeMessage(encodedString);
    expect(decoded).toBe(expectedMessage);
  });
});
