package main

import (
	"fmt"
	"os"
	"path/filepath"
)

func main() {
	target := "."
	if len(os.Args) > 1 {
		target = os.Args[1]
	}
	err := createSkeleton(target)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}
	fmt.Println("Terraform module skeleton created at", target)
}

func createSkeleton(dir string) error {
	files := map[string]string{
		"main.tf": "# Minimal Terraform module\noutput \"example\" {\n  value = \"Hello, Terraform!\"\n}
",
		"variables.tf": "# Variables for the module\nvariable \"example_var\" {\n  description = \"An example variable\"\n  type        = string\n  default     = \"default\"\n}
",
		"outputs.tf": "# Outputs from the module\noutput \"example_output\" {\n  description = \"An example output\"\n  value       = var.example_var\n}
",
		"README.md": "# Terraform Module\n\nThis is a minimal Terraform module skeleton generated by nightly-terraform-skeleton.\n\n## Usage\n\nAdd your resources here.\n\n",
		".gitignore": "# Terraform files\n*.tfstate\n*.tfstate.backup\n",
	}
	for name, content := range files {
		path := filepath.Join(dir, name)
		err := os.MkdirAll(filepath.Dir(path), 0755)
		if err != nil {
			return err
		}
		err = os.WriteFile(path, []byte(content), 0644)
		if err != nil {
			return err
		}
	}
	return nil
}

