import argparse
import string
import sys

# Define the base alphabet for the cipher. This includes common characters.
BASE_ALPHABET = string.ascii_letters + string.digits + string.punctuation + ' '

def generate_cipher_map(key_phrase: str) -> dict[str, str]:
    """
    Generates a deterministic substitution cipher map based on a key phrase.
    The key phrase scrambles the alphabet, making the cipher unique.
    """
    if not key_phrase:
        raise ValueError("Key phrase cannot be empty.")

    # Create a unique character sequence from the key phrase, preserving order of first appearance.
    key_chars_unique = []
    seen_chars = set()
    for char in key_phrase:
        if char not in seen_chars and char in BASE_ALPHABET:
            key_chars_unique.append(char)
            seen_chars.add(char)

    # Create the shuffled alphabet: key_chars_unique + remaining BASE_ALPHABET chars
    shuffled_alphabet_list = list(key_chars_unique)
    for char in BASE_ALPHABET:
        if char not in seen_chars:
            shuffled_alphabet_list.append(char)

    # Ensure the shuffled alphabet has the same length as the base alphabet
    if len(shuffled_alphabet_list) != len(BASE_ALPHABET):
        # This should ideally not happen if filtering is correct, but as a safeguard
        raise RuntimeError("Shuffled alphabet length mismatch. This indicates an internal error.")

    # Create the forward cipher map
    forward_map = {BASE_ALPHABET[i]: shuffled_alphabet_list[i] for i in range(len(BASE_ALPHABET))}
    return forward_map

def encrypt(text: str, key_phrase: str) -> str:
    """
    Encrypts a given text using the cipher generated by the key phrase.
    Characters not in BASE_ALPHABET are left unchanged.
    """
    cipher_map = generate_cipher_map(key_phrase)
    encrypted_chars = []
    for char in text:
        encrypted_chars.append(cipher_map.get(char, char)) # Leave unknown chars as is
    return "".join(encrypted_chars)

def decrypt(encrypted_text: str, key_phrase: str) -> str:
    """
    Decrypts a given encrypted text using the cipher generated by the key phrase.
    Characters not in BASE_ALPHABET are left unchanged.
    """
    cipher_map = generate_cipher_map(key_phrase)
    # Create a reverse map for decryption
    reverse_cipher_map = {v: k for k, v in cipher_map.items()}

    decrypted_chars = []
    for char in encrypted_text:
        decrypted_chars.append(reverse_cipher_map.get(char, char)) # Leave unknown chars as is
    return "".join(decrypted_chars)

def main():
    parser = argparse.ArgumentParser(
        description="Whisperwind Cipher: Encrypt or decrypt messages with a key phrase."
    )
    parser.add_argument("action", choices=["encrypt", "decrypt"], help="Action to perform: encrypt or decrypt.")
    parser.add_argument("text", help="The message to encrypt or decrypt.")
    parser.add_argument("key_phrase", help="The secret key phrase for the cipher.")

    args = parser.parse_args()

    try:
        if args.action == "encrypt":
            result = encrypt(args.text, args.key_phrase)
            print(result)
        elif args.action == "decrypt":
            result = decrypt(args.text, args.key_phrase)
            print(result)
    except ValueError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"An unexpected error occurred: {e}", file=sys.stderr)
        sys.exit(1)

if __name__ == "__main__":
    main()
