[beacons]
beacon_alpha ansible_host=11.0.0.1 ansible_connection=local beacon_id=ALPHA data_path=/tmp/signal_data/alpha.txt
beacon_beta ansible_host=11.0.0.2 ansible_connection=local beacon_id=BETA data_path=/tmp/signal_data/beta.txt

