import argparse

# Default alphabet includes uppercase, lowercase, numbers, and common punctuation/space.
DEFAULT_ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789 .,!?'"
# Default key is a shuffled version of the default alphabet.
# This specific key is generated by shuffling DEFAULT_ALPHABET once.
DEFAULT_KEY = "XyZ0123456789.,!?'ABCDEFGHIJKLMNOPQRSTUVWabcdeFghijklmnOpqrstuvw "

def create_cipher_map(alphabet: str, key: str):
    """
    Creates encryption and decryption maps based on the given alphabet and key.
    Raises ValueError if alphabet and key lengths do not match or if they contain duplicate characters.
    """
    if len(alphabet) != len(key):
        raise ValueError("Alphabet and key must be of the same length.")
    if len(set(alphabet)) != len(alphabet):
        raise ValueError("Alphabet contains duplicate characters.")
    if len(set(key)) != len(key):
        raise ValueError("Key contains duplicate characters.")

    encrypt_map = dict(zip(alphabet, key))
    decrypt_map = dict(zip(key, alphabet))
    return encrypt_map, decrypt_map

def transform_message(message: str, char_map: dict) -> str:
    """
    Transforms a message using the provided character map.
    Characters not in the map are left unchanged.
    """
    transformed_chars = []
    for char in message:
        transformed_chars.append(char_map.get(char, char)) # Leave unknown chars as is
    return "".join(transformed_chars)

def main():
    parser = argparse.ArgumentParser(
        description="Scavenger's Cipher Scribe: Encrypt or decrypt messages using a substitution cipher."
    )
    parser.add_argument(
        "--encrypt", action="store_true", help="Encrypt the message."
    )
    parser.add_argument(
        "--decrypt", action="store_true", help="Decrypt the message."
    )
    parser.add_argument(
        "--message", type=str, required=True, help="The message to encrypt or decrypt."
    )
    parser.add_argument(
        "--alphabet",
        type=str,
        default=DEFAULT_ALPHABET,
        help="The base alphabet string. Must be unique characters.",
    )
    parser.add_argument(
        "--key",
        type=str,
        default=DEFAULT_KEY,
        help="The substitution key string. Must be a permutation of the alphabet.",
    )

    args = parser.parse_args()

    if not (args.encrypt or args.decrypt):
        parser.error("Please specify either --encrypt or --decrypt.")
    if args.encrypt and args.decrypt:
        parser.error("Cannot specify both --encrypt and --decrypt.")

    try:
        encrypt_map, decrypt_map = create_cipher_map(args.alphabet, args.key)
    except ValueError as e:
        print(f"Error creating cipher maps: {e}")
        return

    if args.encrypt:
        result = transform_message(args.message, encrypt_map)
        print(f"Encrypted message: '{result}'")
    elif args.decrypt:
        result = transform_message(args.message, decrypt_map)
        print(f"Decrypted message: '{result}'")


if __name__ == "__main__":
    main()
