[webservers]
web1.example.com ansible_user=chaos_tester
web2.example.com ansible_user=chaos_tester

[databases]
db1.example.com ansible_user=chaos_tester
db2.example.com ansible_user=chaos_tester

[cache]
cache1.example.com ansible_user=chaos_tester

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
