name: "Commit Emoji"
description: "Select an emoji based on commit message length"
inputs:
  message:
    description: "Commit message"
    required: true
outputs:
  emoji:
    description: "Chosen emoji"
runs:
  using: "node12"
  main: "src/index.js"
