from __future__ import annotations

import argparse
import subprocess
from pathlib import Path
from typing import Optional

from . import agent_utils
from .base import AgentBase, AgentContext
from .llm_clients import LLMError, cheap_mix


class BuilderAgent(AgentBase):
    def run(self, ctx: AgentContext) -> int:
        if ctx.issue_number is None:
            print("ERROR: --issue-number is required for the builder agent.")
            return 1
        try:
            issue = agent_utils.get_issue(ctx.repo, ctx.issue_number)
        except agent_utils.GitHubError as exc:
            print(f"ERROR: Failed to fetch issue #{ctx.issue_number}: {exc}")
            return 1
        try:
            prompt = self._compose_prompt(ctx, issue)
            response = cheap_mix(prompt, ctx.models)
            diff = self._extract_diff(response)
            if not diff:
                print("No diff generated by LLM; exiting with no-op.")
                return 2
            self._write_diff(diff)
            print("Diff written to .apocalypsai/last.diff")
            return 0
        except LLMError as exc:
            print(f"ERROR: LLM call failed: {exc}")
            return 1
        except Exception as exc:  # noqa: BLE001
            print(f"ERROR: Unexpected failure: {exc}")
            return 1

    def _compose_prompt(self, ctx: AgentContext, issue: dict) -> str:
        title = issue.get("title") or ""
        body = issue.get("body") or ""
        files = self._git_ls_files()
        readme_excerpt = self._read_file_excerpt("README.md")
        agents_excerpt = self._read_file_excerpt("AGENTS.md")

        prompt_parts = [
            "You are the ApocalypsAI Builder agent. Implement a tiny, safe change.",
            "Follow the repository contract strictly:",
            "- language: Python 3.11 inside agents; packs may vary but stay isolated.",
            "- produce unified diff output only, compatible with git apply.",
            "- touch only packs/*, relevant docs/tests, and supporting files per issue.",
            "- keep diff under ~200 lines and include tests and README updates when applicable.",
            "- never include additional prose outside the diff.",
            "",
            f"Repository: {ctx.repo}",
            f"Issue #{ctx.issue_number}: {title}",
            "Issue body:",
            body,
            "",
            "Repository files (git ls-files):",
            files,
        ]
        if readme_excerpt:
            prompt_parts.extend(["", "README.md excerpt:", readme_excerpt])
        if agents_excerpt:
            prompt_parts.extend(["", "AGENTS.md excerpt:", agents_excerpt])
        prompt_parts.extend(
            [
                "",
                "Requirements:",
                "- Output unified diff only.",
                "- Include tests/docs adjustments when introducing functionality.",
                "- Avoid network calls in tests; mention mocks with `# Mock rationale:` comments where needed.",
                "- If no change is necessary, respond exactly with `NO_CHANGES`.",
            ]
        )
        return "\n".join(prompt_parts)

    def _git_ls_files(self) -> str:
        try:
            output = subprocess.check_output(["git", "ls-files"], text=True, stderr=subprocess.DEVNULL)
            lines = output.strip().splitlines()
            return "\n".join(lines[:200])
        except subprocess.CalledProcessError:
            return ""

    def _read_file_excerpt(self, path: str, max_chars: int = 2000) -> str:
        file_path = Path(path)
        if not file_path.exists():
            return ""
        text = file_path.read_text(encoding="utf-8", errors="ignore")
        return text[:max_chars]

    def _extract_diff(self, response: str) -> str:
        cleaned = response.strip()
        if cleaned == "NO_CHANGES":
            return ""
        diff = self._extract_from_fence(cleaned)
        if diff:
            return diff
        marker = cleaned.find("--- ")
        if marker != -1:
            diff_body = cleaned[marker:].strip()
            return diff_body
        return ""

    def _extract_from_fence(self, text: str) -> str:
        blocks = []
        fence = "```"
        idx = 0
        while True:
            start = text.find(fence, idx)
            if start == -1:
                break
            lang_end = text.find("\n", start)
            if lang_end == -1:
                break
            lang = text[start + 3 : lang_end].strip()
            end = text.find(fence, lang_end)
            if end == -1:
                break
            block = text[lang_end + 1 : end].strip()
            idx = end + 3
            if lang in {"diff", ""}:
                blocks.append(block)
        for block in blocks:
            if block.startswith("--- "):
                return block
        return blocks[0] if blocks else ""

    def _write_diff(self, diff: str) -> None:
        target_dir = Path(".apocalypsai")
        target_dir.mkdir(parents=True, exist_ok=True)
        target_path = target_dir / "last.diff"
        content = diff if diff.endswith("\n") else f"{diff}\n"
        target_path.write_text(content, encoding="utf-8")


def _parse_models(value: Optional[str]) -> Optional[dict]:
    if not value:
        return None
    pairs = {}
    entries = value.split(",")
    for entry in entries:
        if "=" not in entry:
            continue
        provider, model = entry.split("=", 1)
        provider = provider.strip()
        model = model.strip()
        if provider and model:
            pairs[provider] = model
    return pairs or None


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo", required=True)
    parser.add_argument("--issue-number", type=int)
    parser.add_argument("--pr", type=int)
    parser.add_argument("--mode")
    parser.add_argument(
        "--models",
        help="Comma-separated provider=model overrides (e.g. groq=modelA,openrouter=modelB)",
    )
    args = parser.parse_args()
    ctx = AgentContext(
        repo=args.repo,
        issue_number=args.issue_number,
        pr_number=args.pr,
        mode=args.mode,
        models=_parse_models(args.models),
    )
    code = BuilderAgent().run(ctx)
    raise SystemExit(code)


if __name__ == "__main__":
    main()
