from __future__ import annotations

import argparse
import subprocess
from pathlib import Path
from typing import Optional

from .base import AgentBase, AgentContext
from .llm_clients import LLMError, cheap_mix


class IntegratorAgent(AgentBase):
    def run(self, ctx: AgentContext) -> int:
        if (ctx.mode or "").lower() != "nightly":
            print("ERROR: --mode nightly is required for the integrator agent.")
            return 1
        try:
            prompt = self._compose_prompt(ctx)
            response = cheap_mix(prompt, ctx.models)
            diff = self._extract_diff(response)
            if not diff:
                print("No diff generated by LLM; exiting with no-op.")
                return 2
            self._write_diff(diff)
            print("Diff written to .apocalypsai/last.diff")
            return 0
        except LLMError as exc:
            print(f"ERROR: LLM call failed: {exc}")
            return 1
        except Exception as exc:  # noqa: BLE001
            print(f"ERROR: Unexpected failure: {exc}")
            return 1

    def _compose_prompt(self, ctx: AgentContext) -> str:
        files = self._git_ls_files()
        readme_excerpt = self._read_file_excerpt("README.md")
        agents_excerpt = self._read_file_excerpt("AGENTS.md")
        prompt_parts = [
            "You are the ApocalypsAI Nightly Integrator agent.",
            "Scan the repository for tiny, reversible improvements:",
            "- fix typos, missing docstrings, or formatting nits.",
            "- add micro tests or examples if obvious gaps exist.",
            "- never rename large structures or refactor widely.",
            "- keep diff extremely small (≤ 200 LOC) and easy to revert.",
            "- include documentation or tests when adjusting code.",
            "- output unified diff only; no surrounding prose.",
            "",
            f"Repository: {ctx.repo}",
            "Repository files (git ls-files):",
            files,
        ]
        if readme_excerpt:
            prompt_parts.extend(["", "README.md excerpt:", readme_excerpt])
        if agents_excerpt:
            prompt_parts.extend(["", "AGENTS.md excerpt:", agents_excerpt])
        prompt_parts.extend(
            [
                "",
                "If no safe improvement is possible today, respond exactly `NO_CHANGES`.",
                "Otherwise produce a unified diff ready for git apply.",
            ]
        )
        return "\n".join(prompt_parts)

    def _git_ls_files(self) -> str:
        try:
            output = subprocess.check_output(["git", "ls-files"], text=True, stderr=subprocess.DEVNULL)
            lines = output.strip().splitlines()
            return "\n".join(lines[:200])
        except subprocess.CalledProcessError:
            return ""

    def _read_file_excerpt(self, path: str, max_chars: int = 2000) -> str:
        file_path = Path(path)
        if not file_path.exists():
            return ""
        text = file_path.read_text(encoding="utf-8", errors="ignore")
        return text[:max_chars]

    def _extract_diff(self, response: str) -> str:
        cleaned = response.strip()
        if cleaned == "NO_CHANGES":
            return ""
        diff = self._extract_from_fence(cleaned)
        if diff:
            return diff
        marker = cleaned.find("--- ")
        if marker != -1:
            diff_body = cleaned[marker:].strip()
            return diff_body
        return ""

    def _extract_from_fence(self, text: str) -> str:
        blocks = []
        fence = "```"
        idx = 0
        while True:
            start = text.find(fence, idx)
            if start == -1:
                break
            lang_end = text.find("\n", start)
            if lang_end == -1:
                break
            lang = text[start + 3 : lang_end].strip()
            end = text.find(fence, lang_end)
            if end == -1:
                break
            block = text[lang_end + 1 : end].strip()
            idx = end + 3
            if lang in {"diff", ""}:
                blocks.append(block)
        for block in blocks:
            if block.startswith("--- "):
                return block
        return blocks[0] if blocks else ""

    def _write_diff(self, diff: str) -> None:
        target_dir = Path(".apocalypsai")
        target_dir.mkdir(parents=True, exist_ok=True)
        target_path = target_dir / "last.diff"
        content = diff if diff.endswith("\n") else f"{diff}\n"
        target_path.write_text(content, encoding="utf-8")


def _parse_models(value: Optional[str]) -> Optional[dict]:
    if not value:
        return None
    pairs = {}
    entries = value.split(",")
    for entry in entries:
        if "=" not in entry:
            continue
        provider, model = entry.split("=", 1)
        provider = provider.strip()
        model = model.strip()
        if provider and model:
            pairs[provider] = model
    return pairs or None


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo", required=True)
    parser.add_argument("--issue-number", type=int)
    parser.add_argument("--pr", type=int)
    parser.add_argument("--mode")
    parser.add_argument(
        "--models",
        help="Comma-separated provider=model overrides (e.g. groq=modelA,openrouter=modelB)",
    )
    args = parser.parse_args()
    ctx = AgentContext(
        repo=args.repo,
        issue_number=args.issue_number,
        pr_number=args.pr,
        mode=args.mode,
        models=_parse_models(args.models),
    )
    code = IntegratorAgent().run(ctx)
    raise SystemExit(code)


if __name__ == "__main__":
    main()
