import { execSync } from 'child_process';
import fs from 'fs';
import path from 'path';

describe('Nightly TypeScript Type Guard Generator', () => {
  const inputDir = path.join(__dirname, 'fixtures');
  const outputDir = path.join(__dirname, 'generated');

  beforeAll(() => {
    // Ensure output directory exists
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir);
    }
  });

  afterEach(() => {
    // Clean up generated files after each test
    fs.readdirSync(outputDir).forEach(file => {
      fs.unlinkSync(path.join(outputDir, file));
    });
  });

  it('should generate type guards for simple interfaces', () => {
    const inputFile = path.join(inputDir, 'simple-interfaces.ts');
    const outputFile = path.join(outputDir, 'simple-guards.ts');

    // Mock rationale: We are simulating the execution of the CLI tool.
    // This avoids needing to install it globally or manage complex execution environments for tests.
    execSync(`npx ts-node src/main.ts --input ${inputFile} --output ${outputFile}`);

    const generatedContent = fs.readFileSync(outputFile, 'utf-8');
    const expectedContent = fs.readFileSync(path.join(inputDir, 'simple-interfaces.expected.ts'), 'utf-8');

    expect(generatedContent.trim()).toBe(expectedContent.trim());
  });

  it('should generate type guards for interfaces with union types', () => {
    const inputFile = path.join(inputDir, 'union-interfaces.ts');
    const outputFile = path.join(outputDir, 'union-guards.ts');

    execSync(`npx ts-node src/main.ts --input ${inputFile} --output ${outputFile}`);

    const generatedContent = fs.readFileSync(outputFile, 'utf-8');
    const expectedContent = fs.readFileSync(path.join(inputDir, 'union-interfaces.expected.ts'), 'utf-8');

    expect(generatedContent.trim()).toBe(expectedContent.trim());
  });

  it('should generate type guards for interfaces with array types', () => {
    const inputFile = path.join(inputDir, 'array-interfaces.ts');
    const outputFile = path.join(outputDir, 'array-guards.ts');

    execSync(`npx ts-node src/main.ts --input ${inputFile} --output ${outputFile}`);

    const generatedContent = fs.readFileSync(outputFile, 'utf-8');
    const expectedContent = fs.readFileSync(path.join(inputDir, 'array-interfaces.expected.ts'), 'utf-8');

    expect(generatedContent.trim()).toBe(expectedContent.trim());
  });

  it('should handle interfaces with mixed types including arrays and unions', () => {
    const inputFile = path.join(inputDir, 'mixed-interfaces.ts');
    const outputFile = path.join(outputDir, 'mixed-guards.ts');

    execSync(`npx ts-node src/main.ts --input ${inputFile} --output ${outputFile}`);

    const generatedContent = fs.readFileSync(outputFile, 'utf-8');
    const expectedContent = fs.readFileSync(path.join(inputDir, 'mixed-interfaces.expected.ts'), 'utf-8');

    expect(generatedContent.trim()).toBe(expectedContent.trim());
  });

  it('should throw an error if input or output is missing', () => {
    // Mock rationale: We are testing the CLI argument parsing and error handling.
    // We expect the process to exit with a non-zero code and log an error message.
    expect(() => {
      execSync('npx ts-node src/main.ts --input fixtures/simple-interfaces.ts');
    }).toThrow();

    expect(() => {
      execSync('npx ts-node src/main.ts --output generated/test.ts');
    }).toThrow();
  });
});

// Mock fixtures for testing
// These files would be placed in a 'fixtures' directory next to this test file.

// fixtures/simple-interfaces.ts
/*
interface User {
  id: number;
  name: string;
}

interface Product {
  sku: string;
  price: number;
}
*/

// fixtures/simple-interfaces.expected.ts
/*
// Generated by ApocalypsAI Nightly TypeScript Type Guard Generator

interface User {
  id: number;
  name: string;
}

interface Product {
  sku: string;
  price: number;
}

export function isUser(obj: any): obj is User {
  return (
    typeof obj === 'object' &&
    obj !== null &&
    'id' in obj && typeof obj.id === 'number' &&
    'name' in obj && typeof obj.name === 'string'
  );
}

export function isProduct(obj: any): obj is Product {
  return (
    typeof obj === 'object' &&
    obj !== null &&
    'sku' in obj && typeof obj.sku === 'string' &&
    'price' in obj && typeof obj.price === 'number'
  );
}
*/

// fixtures/union-interfaces.ts
/*
interface Status {
  code: number;
  message?: string;
}

interface Error {
  errorCode: string;
  details: string;
}

interface ApiResponse {
  status: Status | Error;
}
*/

// fixtures/union-interfaces.expected.ts
/*
// Generated by ApocalypsAI Nightly TypeScript Type Guard Generator

interface Status {
  code: number;
  message?: string;
}

interface Error {
  errorCode: string;
  details: string;
}

interface ApiResponse {
  status: Status | Error;
}

export function isStatus(obj: any): obj is Status {
  return (
    typeof obj === 'object' &&
    obj !== null &&
    'code' in obj && typeof obj.code === 'number'
  );
}

export function isError(obj: any): obj is Error {
  return (
    typeof obj === 'object' &&
    obj !== null &&
    'errorCode' in obj && typeof obj.errorCode === 'string' &&
    'details' in obj && typeof obj.details === 'string'
  );
}

export function isApiResponse(obj: any): obj is ApiResponse {
  return (
    typeof obj === 'object' &&
    obj !== null &&
    'status' in obj && (isStatus(obj.status) || isError(obj.status))
  );
}
*/

// fixtures/array-interfaces.ts
/*
interface Item {
  name: string;
  quantity: number;
}

interface ShoppingCart {
  id: string;
  items: Item[];
}
*/

// fixtures/array-interfaces.expected.ts
/*
// Generated by ApocalypsAI Nightly TypeScript Type Guard Generator

interface Item {
  name: string;
  quantity: number;
}

interface ShoppingCart {
  id: string;
  items: Item[];
}

export function isItem(obj: any): obj is Item {
  return (
    typeof obj === 'object' &&
    obj !== null &&
    'name' in obj && typeof obj.name === 'string' &&
    'quantity' in obj && typeof obj.quantity === 'number'
  );
}

export function isShoppingCart(obj: any): obj is ShoppingCart {
  return (
    typeof obj === 'object' &&
    obj !== null &&
    'id' in obj && typeof obj.id === 'string' &&
    'items' in obj && Array.isArray(obj.items) && obj.items.every((item: any) => isItem(item))
  );
}
*/

// fixtures/mixed-interfaces.ts
/*
interface UserProfile {
  userId: number;
  tags: string[];
  preferences: { theme: 'dark' | 'light'; notifications: boolean };
}

interface AdminPanel {
  panelId: string;
  users: UserProfile[];
  isActive: boolean;
}
*/

// fixtures/mixed-interfaces.expected.ts
/*
// Generated by ApocalypsAI Nightly TypeScript Type Guard Generator

interface UserProfile {
  userId: number;
  tags: string[];
  preferences: { theme: 'dark' | 'light'; notifications: boolean };
}

interface AdminPanel {
  panelId: string;
  users: UserProfile[];
  isActive: boolean;
}

export function isUserProfile(obj: any): obj is UserProfile {
  return (
    typeof obj === 'object' &&
    obj !== null &&
    'userId' in obj && typeof obj.userId === 'number' &&
    'tags' in obj && Array.isArray(obj.tags) && obj.tags.every((item: any) => typeof item === 'string') &&
    'preferences' in obj && typeof obj.preferences === 'object' &&
    obj.preferences !== null &&
    'theme' in obj.preferences && (obj.preferences.theme === 'dark' || obj.preferences.theme === 'light') &&
    'notifications' in obj.preferences && typeof obj.preferences.notifications === 'boolean'
  );
}

export function isAdminPanel(obj: any): obj is AdminPanel {
  return (
    typeof obj === 'object' &&
    obj !== null &&
    'panelId' in obj && typeof obj.panelId === 'string' &&
    'users' in obj && Array.isArray(obj.users) && obj.users.every((item: any) => isUserProfile(item)) &&
    'isActive' in obj && typeof obj.isActive === 'boolean'
  );
}
*/
