import { render, screen, fireEvent } from '@testing-library/react';
import { describe, it, expect } from 'vitest';
import App from '../src/App.jsx';

describe('App', () => {
  it('renders the main title and input elements', () => {
    render(<App />);
    expect(screen.getByText(/Temporal Echo Visualizer/i)).toBeInTheDocument();
    expect(screen.getByPlaceholderText(/Enter Temporal Anchor/i)).toBeInTheDocument();
    expect(screen.getByRole('button', { name: /Generate Echoes/i })).toBeInTheDocument();
  });

  it('displays echoes after entering an anchor and clicking the button', async () => {
    render(<App />);
    const input = screen.getByPlaceholderText(/Enter Temporal Anchor/i);
    const button = screen.getByRole('button', { name: /Generate Echoes/i });

    // Mock rationale: The generateDeterministicEchoes function in App.jsx is designed
    // to produce consistent output for a given input, making tests deterministic without
    // needing external mocks for randomness.
    const testAnchor = 'The Old World';
    fireEvent.change(input, { target: { value: testAnchor } });
    fireEvent.click(button);

    // Expect specific echoes based on the deterministic generation logic for 'The Old World'
    // These assertions rely on the internal, predictable logic of generateDeterministicEchoes.
    expect(await screen.findByText(/Past Whisper/i)).toBeInTheDocument();
    expect(screen.getByText(/Future Ripple/i)).toBeInTheDocument();
    expect(screen.getByText(/Distortion Index/i)).toBeInTheDocument();

    // Check for specific content generated by the deterministic function for 'The Old World'
    // 'The Old World' has length 13, charCodeAt(0) is 84, charCodeAt(end) is 100. Seed = 13 + 84 + 100 = 197.
    // pastWhispers[197 % 7 = 0] -> "A faint memory of plentiful harvests."
    // futureRipples[(197 + 1) % 7 = 1] -> "The faint scent of rain on parched earth."
    expect(screen.getByText(/A faint memory of plentiful harvests./i)).toBeInTheDocument();
    expect(screen.getByText(/The faint scent of rain on parched earth./i)).toBeInTheDocument();
    expect(screen.getByText(/units of temporal flux./i)).toBeInTheDocument();
  });

  it('clears echoes if input is empty and button is clicked', async () => {
    render(<App />);
    const input = screen.getByPlaceholderText(/Enter Temporal Anchor/i);
    const button = screen.getByRole('button', { name: /Generate Echoes/i });

    // First, generate some echoes
    fireEvent.change(input, { target: { value: 'Temporary Anchor' } });
    fireEvent.click(button);
    expect(await screen.findByText(/Past Whisper/i)).toBeInTheDocument();

    // Then, clear the input and click again
    fireEvent.change(input, { target: { value: '' } });
    fireEvent.click(button);

    expect(screen.queryByText(/Past Whisper/i)).not.toBeInTheDocument();
    expect(screen.queryByText(/Future Ripple/i)).not.toBeInTheDocument();
    expect(screen.queryByText(/Distortion Index/i)).not.toBeInTheDocument();
    expect(screen.getByText(/No echoes detected for this anchor. Try another!/i)).toBeInTheDocument();
  });

  it('does not display "No echoes detected" initially', () => {
    render(<App />);
    expect(screen.queryByText(/No echoes detected for this anchor. Try another!/i)).not.toBeInTheDocument();
  });
});
