import { render, screen, fireEvent } from '@testing-library/react';
import App from '../src/App';

// Mock rationale: The hashString and createPseudoRandomGenerator functions are internal
// and deterministic. We don't need to mock them directly, but we can test the output
// of generateEchoData indirectly by checking the visualizer's rendering.
// For a more complex app, external API calls would be mocked here.

describe('App Component', () => {
  test('renders the main title', () => {
    render(<App />);
    expect(screen.getByText(/Temporal Echo Visualizer/i)).toBeInTheDocument();
  });

  test('allows user to input a coordinate and visualize echoes', async () => {
    render(<App />);

    const inputElement = screen.getByLabelText(/Temporal Coordinate Input/i);
    const buttonElement = screen.getByRole('button', { name: /Visualize Echoes/i });

    fireEvent.change(inputElement, { target: { value: 'test-coordinate' } });
    fireEvent.click(buttonElement);

    // Expect the echo display to appear with the coordinate
    expect(await screen.findByText(/Echoes from: "test-coordinate"/i)).toBeInTheDocument();
    // Expect echo bars to be rendered (10 bars are generated by default)
    const echoBars = screen.getAllByLabelText(/Echo bar \d+ with strength \d+\.\d+/i);
    expect(echoBars).toHaveLength(10);
  });

  test('does not display echoes initially', () => {
    render(<App />);
    expect(screen.queryByText(/Echoes from:/i)).not.toBeInTheDocument();
    expect(screen.queryByLabelText(/Echo bar/i)).not.toBeInTheDocument();
  });

  test('displays a message if an empty coordinate is submitted', async () => {
    render(<App />);

    const inputElement = screen.getByLabelText(/Temporal Coordinate Input/i);
    const buttonElement = screen.getByRole('button', { name: /Visualize Echoes/i });

    fireEvent.change(inputElement, { target: { value: '' } });
    fireEvent.click(buttonElement);

    expect(await screen.findByText(/No echoes detected for empty coordinate/i)).toBeInTheDocument();
    expect(screen.queryByLabelText(/Echo bar/i)).not.toBeInTheDocument();
  });
});
