import unittest
import datetime
from unittest.mock import patch

# Mock rationale: we patch datetime.date.today to a fixed date so the test is deterministic and offline.
from src.forecast import get_forecast

class TestEmojiForecast(unittest.TestCase):
    def test_known_date(self):
        # 2025-01-01 is a known anchor date; the expected forecast is derived from the algorithm.
        date = datetime.date(2025, 1, 1)
        forecast = get_forecast(date)
        # The exact emojis are deterministic; compute expected manually using the same logic.
        # For clarity we embed the expected string directly.
        expected = "☀️ 🌤️ ⛅"  # <-- this value was generated by running the function once.
        self.assertEqual(forecast, expected)

    @patch('src.forecast.datetime.date')
    def test_today_forecast_uses_mocked_date(self, mock_date):
        # Mock rationale: ensure that calling get_forecast without arguments uses the mocked today.
        mock_date.today.return_value = datetime.date(2023, 12, 31)
        mock_date.fromisoformat.side_effect = datetime.date.fromisoformat
        forecast = get_forecast(mock_date.today())
        expected = "🌧️ ⛈️ 🌨️"  # <-- deterministic result for 2023-12-31
        self.assertEqual(forecast, expected)

if __name__ == "__main__":
    unittest.main()
