#!/usr/bin/env bash
set -euo pipefail

# Default configuration
CACHE_DIR="${APT_CACHE_DIR:-/var/cache/apt/archives}"
MAX_DAYS="${MAX_DAYS:-7}"
INSTALL_CRON=false

# Parse optional flag
if [[ "${1-}" == "--install" ]]; then
  INSTALL_CRON=true
fi

# Function to perform the cleanup
cleanup() {
  local now epoch_age file_mod file_path age
  now=$(date +%s)
  echo "⚠️  Apocalypse warning: The package graveyard will be purged!"

  # Find .deb files and evaluate their age
  find "$CACHE_DIR" -type f -name "*.deb" -printf "%T@ %p\n" | while read -r file_mod file_path; do
    # file_mod is seconds since epoch with fractional part; strip fraction
    epoch_age=${file_mod%.*}
    age=$(( (now - epoch_age) / 86400 ))
    if (( age > MAX_DAYS )); then
      echo "Removing $file_path (age ${age}d)"
      rm -f "$file_path"
    fi
  done
  echo "Cleanup complete. Next purge in 24h."
}

# Function to install a daily cron job (requires root)
install_cron() {
  local cron_file="/etc/cron.d/apt-cleanup"
  echo "# Daily apt cache cleanup – generated by nightly-apt-cleanup-scheduler" | sudo tee "$cron_file" > /dev/null
  echo "0 2 * * * root $(realpath "$0")" | sudo tee -a "$cron_file" > /dev/null
  echo "Cron job installed at $cron_file (runs at 02:00 daily)."
}

# Execute actions based on flags
if $INSTALL_CRON; then
  install_cron
else
  cleanup
fi
