run "basic_deployment" {
  module "waypoint" {
    source = "../src"
    bucket_name = "test-waypoint-beacon-bucket"
    region = "us-east-1"
    content_file_path = "../src/waypoint_content/index.html"
  }

  # Mock rationale: We mock the AWS provider to prevent actual cloud resource creation
  # and ensure tests are deterministic and offline. This simulates the outputs
  # that would be generated by S3 and CloudFront without incurring costs or delays.
  provider "aws" {
    alias = "mock"
    mock_outputs = {
      s3_bucket_website_configuration = {
        website_endpoint = "http://test-waypoint-beacon-bucket.s3-website-us-east-1.amazonaws.com"
      }
      cloudfront_distribution = {
        domain_name = "d1234567890abc.cloudfront.net"
      }
    }
  }

  assert {
    condition     = module.waypoint.s3_bucket_endpoint == "http://test-waypoint-beacon-bucket.s3-website-us-east-1.amazonaws.com"
    error_message = "S3 bucket endpoint output does not match expected mock value."
  }

  assert {
    condition     = module.waypoint.cloudfront_domain_name == "d1234567890abc.cloudfront.net"
    error_message = "CloudFront domain name output does not match expected mock value."
  }
}
