import { Fortune } from './types';

export const fortunes: Fortune[] = [
  { message: "The best code is no code.", category: "wisdom" },
  { message: "Debugging is like being a detective in a crime movie where you are also the murderer.", category: "debugging" },
  { message: "It works on my machine. (Famous last words)", category: "deployment" },
  { message: "Whitespace is not your enemy, it's your friend. Use it wisely.", category: "general" },
  { message: "Before you optimize, make it work. Before you make it work, make it simple.", category: "wisdom" },
  { message: "The only thing worse than a bug is a bug that looks like a feature.", category: "debugging" },
  { message: "Automated tests are like tiny, diligent guardians of your sanity.", category: "wisdom" },
  { message: "A successful deployment is 90% preparation, 10% prayer.", category: "deployment" },
  { message: "If you can't explain it simply, you don't understand it well enough.", category: "wisdom" },
  { message: "The compiler is your friend. It just has a weird way of showing it.", category: "general" },
  { message: "When in doubt, console.log().", category: "debugging" },
  { message: "Your code is like a garden. Weeds will grow if you don't tend to it.", category: "wisdom" },
  { message: "The most exciting phrase to hear in science, the one that heralds new discoveries, is not 'Eureka!' but 'That's funny...'.", category: "debugging" },
  { message: "The first 90% of the code accounts for the first 90% of the development time. The remaining 10% of the code accounts for the other 90% of the development time.", category: "general" },
  { message: "Refactoring is like cleaning your room. It's messy at first, but worth it.", category: "wisdom" },
  { message: "Deployment day: May your logs be clear and your rollback plan be robust.", category: "deployment" },
  { message: "The only constant in software development is change.", category: "general" },
  { message: "Beware of the feature creep, for it devours timelines.", category: "wisdom" },
  { message: "A semicolon walks into a bar, takes a seat. The bartender asks, 'What can I get you?' The semicolon replies, 'Just a break.'", category: "general" },
  { message: "The best way to predict the future is to implement it.", category: "wisdom" },
  { message: "If debugging is the process of removing software bugs, then programming must be the process of putting them in.", category: "debugging" },
  { message: "The cloud is just someone else's computer.", category: "deployment" },
  { message: "Write tests. Your future self will thank you.", category: "wisdom" },
  { message: "The most dangerous phrase in the language is 'we've always done it this way.'", category: "general" },
  { message: "Premature optimization is the root of all evil.", category: "wisdom" },
  { message: "There are only two hard things in computer science: cache invalidation and naming things.", category: "general" },
  { message: "Good design is as little design as possible.", category: "wisdom" },
  { message: "The customer is always right, until they ask for something impossible.", category: "general" },
  { message: "Measure twice, cut once. Deploy once, rollback never (hopefully).", category: "deployment" },
  { message: "The more you learn, the more you realize how much you don't know.", category: "wisdom" },
  { message: "A good programmer is someone who always looks both ways before crossing a one-way street.", category: "general" },
  { message: "Don't comment bad code\u2014rewrite it.", category: "wisdom" },
  { message: "The best way to get a project done faster is to start sooner.", category: "general" },
  { message: "If you think your users are dumb, your users are probably smarter than you think.", category: "general" },
  { message: "The only true wisdom is in knowing you know nothing. Except how to fix that merge conflict.", category: "wisdom" },
  { message: "Version control: because 'oops' happens.", category: "general" },
  { message: "The compiler never lies, but it can be very misleading.", category: "debugging" },
  { message: "Continuous integration is not a luxury, it's a necessity.", category: "deployment" },
  { message: "Documentation is like a good wine; it gets better with age, but only if you keep it updated.", category: "general" },
  { message: "The path to enlightenment is paved with well-tested code.", category: "wisdom" },
  { message: "When you find yourself in a hole, stop digging. Unless it's for a root cause.", category: "debugging" },
  { message: "Microservices are great, until you have to debug a distributed transaction.", category: "deployment" },
  { message: "The greatest enemy of knowledge is not ignorance, it is the illusion of knowledge.", category: "wisdom" },
  { message: "If it's not in version control, it doesn't exist.", category: "general" },
  { message: "The only way to do great work is to love what you do. Or at least tolerate the bugs.", category: "wisdom" },
  { message: "A byte walks into a bar and asks for a drink. The bartender says, 'Sure, what can I get you?' The byte replies, 'Make me a double.'", category: "general" },
  { message: "The best way to predict the future is to create it. With a solid CI/CD pipeline.", category: "deployment" },
  { message: "Don't repeat yourself. Unless you're writing a loop.", category: "wisdom" },
  { message: "The code you write today will be legacy code tomorrow.", category: "general" },
  { message: "The most effective debugging tool is still a carefully thought-out print statement.", category: "debugging" }
];
