#!/bin/bash

# Nightly Digital Bugout Bag Generator

# Default values
DEFAULT_TOOLS="git,jq,curl,vim,python3"
DEFAULT_NAME="my-digital-bag"
DEFAULT_OUTPUT_DIR="./my-digital-bag"
BASE_IMAGE="alpine/git:latest" # A lightweight image with git pre-installed

TOOLS="$DEFAULT_TOOLS"
BAG_NAME="$DEFAULT_NAME"
OUTPUT_DIR="$DEFAULT_OUTPUT_DIR"

# Function to display help message
show_help() {
    echo "Usage: $0 [OPTIONS]"
    echo ""
    echo "Generates a Docker-Compose setup for a portable digital survival toolkit."
    echo ""
    echo "Options:"
    echo "  -t <tools>       Comma-separated list of tools to include (default: \"$DEFAULT_TOOLS\")"
    echo "                   Example: \"git,jq,curl,python3\""
    echo "  -n <name>        Name for your bugout bag (default: \"$DEFAULT_NAME\")"
    echo "  -o <output_dir>  Output directory for the generated files (default: \"$DEFAULT_OUTPUT_DIR\")"
    echo "  -h               Display this help message"
    echo ""
    echo "Example:"
    echo "  $0 -t \"git,node,npm\" -n \"web-dev-bag\" -o \"./web-dev-project\""
    exit 0
}

# Parse command-line arguments
while getopts "t:n:o:h" opt; do
    case "$opt" in
        t) TOOLS="$OPTARG" ;;
        n) BAG_NAME="$OPTARG" ;;
        o) OUTPUT_DIR="$OPTARG" ;;
        h) show_help ;;
        *) echo "Invalid option: -$OPTARG" >&2; show_help ;;
    esac
done

# Create output directory
mkdir -p "$OUTPUT_DIR/data" # Create data directory for volume mount

# --- Generate Dockerfile ---
DOCKERFILE_PATH="$OUTPUT_DIR/Dockerfile"
echo "Generating Dockerfile at $DOCKERFILE_PATH"
cat <<EOF > "$DOCKERFILE_PATH"
# Dockerfile for your Digital Bugout Bag: $BAG_NAME
# Generated by ApocalypsAI Nightly Integrator

FROM $BASE_IMAGE

LABEL maintainer="ApocalypsAI Nightly Integrator"
LABEL description="A portable digital survival toolkit with essential CLI tools."

# Install specified tools
# Using apk for Alpine Linux
RUN apk update && apk add --no-cache \\
    $(echo "$TOOLS" | tr ',' ' ') && \\
    rm -rf /var/cache/apk/*

# Set a working directory
WORKDIR /app

# Custom welcome message (whimsical touch!)
RUN echo "Welcome to your Digital Bugout Bag: $BAG_NAME!" > /etc/motd

# Default command when entering the container
CMD ["/bin/bash"]
EOF

# --- Generate docker-compose.yml ---
DOCKER_COMPOSE_PATH="$OUTPUT_DIR/docker-compose.yml"
echo "Generating docker-compose.yml at $DOCKER_COMPOSE_PATH"
cat <<EOF > "$DOCKER_COMPOSE_PATH"
# docker-compose.yml for your Digital Bugout Bag: $BAG_NAME
# Generated by ApocalypsAI Nightly Integrator

version: '3.8'
services:
  $BAG_NAME:
    build: .
    container_name: $BAG_NAME-container
    volumes:
      - ./data:/app/data # Persistent storage for your bag's contents
    stdin_open: true # Keep stdin open even if not attached
    tty: true        # Allocate a pseudo-TTY
    # Optional: If you need to expose ports for any tools (e.g., a local web server)
    # ports:
    #   - "8080:8080"
EOF

# --- Generate run_bag.sh ---
RUN_BAG_SCRIPT_PATH="$OUTPUT_DIR/run_bag.sh"
echo "Generating run_bag.sh at $RUN_BAG_SCRIPT_PATH"
cat <<EOF > "$RUN_BAG_SCRIPT_PATH"
#!/bin/bash

# Convenience script to build and run your Digital Bugout Bag: $BAG_NAME
# Generated by ApocalypsAI Nightly Integrator

echo "Building Docker image for $BAG_NAME..."
docker-compose build

echo "Starting your Digital Bugout Bag: $BAG_NAME. Type 'exit' to leave."
docker-compose run --rm $BAG_NAME /bin/bash
EOF
chmod +x "$RUN_BAG_SCRIPT_PATH"

# --- Generate README.md for the specific bag ---
BAG_README_PATH="$OUTPUT_DIR/README.md"
echo "Generating README.md for $BAG_NAME at $BAG_README_PATH"
cat <<EOF > "$BAG_README_PATH"
# My Digital Bugout Bag: $BAG_NAME

This directory contains your personalized digital survival toolkit, generated by the ApocalypsAI Nightly Integrator.

## Included Tools

```
$(echo "$TOOLS" | tr ',' '\n')
```

## How to Use

1.  **Navigate to this directory**:
    ```bash
    cd $(basename "$OUTPUT_DIR")
    ```

2.  **Run your bag**:
    ```bash
    ./run_bag.sh
    ```
    This will build the Docker image (if not already built) and drop you into a shell inside the container.

3.  **Access your persistent data**:
    Any files you create or modify in the `/app/data` directory inside the container will be persisted in the `./data` directory on your host machine.

4.  **Exit the bag**:
    Simply type `exit` in the container's shell.

## Files

*   `Dockerfile`: Defines the container image.
*   `docker-compose.yml`: Orchestrates the container.
*   `run_bag.sh`: Convenience script to build and run.
*   `data/`: Directory for persistent data.

Enjoy your portable digital sanctuary!
EOF

echo "Digital Bugout Bag '$BAG_NAME' generated successfully in '$OUTPUT_DIR'."
echo "To use it, navigate to '$OUTPUT_DIR' and run './run_bag.sh'."
