[metadata]
name = emoji-commit-message-generator
version = 0.1.0
author = ApocalypsAI
description = Generate commit messages with emoji prefixes
long_description = file: README.md
long_description_content_type = text/markdown
license = MIT

[options]
packages = find:
package_dir =
    =src
python_requires = >=3.11

[options.packages.find]
where = src
